make gpgp detect user roles automatically

diff --git a/bin/gpgp b/bin/gpgp
--- a/bin/gpgp
+++ b/bin/gpgp
@@ -10,6 +10,21 @@ set -euo pipefail
 
 GPG='gpg'
 
+_join() {
+  local joint="${1:-}"
+  shift
+  local i=0
+  for e in "$@"; do
+    echo -n "${e}"
+    ((i++))
+    if [[ "${i}" != "$#" ]]; then
+      echo -n "${joint}"
+    else
+      echo
+    fi
+  done
+}
+
 gpgp::role_path() {
   echo "${DAVINCI_GPGP_PATH}/gpgp/roles/${1:-}"
 }
@@ -26,13 +41,21 @@ gpgp::ls_roles() {
   find "$(gpgp::role_path)" -type f -printf '%f\n' | sort
 }
 
+gpgp::ls_pub_keys() {
+  find "$(gpgp::pub_key_path)" -type f -printf '%f\n' | sort
+}
+
 gpgp::is_role() {
   gpgp::ls_roles | grep -qP "^${1}$"
 }
 
-gpgp::match_pub_key() {
+gpgp::is_pub_key_auto_role() {
+  gpgp::ls_pub_keys | grep -qP "^${1}@.+\.pub$"
+}
+
+gpgp::is_pub_key() {
   local thing="${1}"
-  find "$(gpgp::pub_key_path)" -type f -printf '%f\n' | grep -q "${thing}"
+  gpgp::ls_pub_keys | grep -q "${thing}"
 }
 
 gpgp::is_comment() {
@@ -40,24 +63,36 @@ gpgp::is_comment() {
   [[ "${thing}" == '#'* ]]
 }
 
+gpgp::get_id_from_key_fname() {
+  local fname="$1"
+  echo "${fname}" | sed -n -e's/.*id:\([0-9A-Z]\+\).*/\1/p'
+}
+
+gpgp::get_id_from_auto_role() {
+  local auto_role="$1"
+  local fname="$(gpgp::ls_pub_keys | grep -P "^${auto_role}@.+\.pub$")"
+  gpgp::get_id_from_key_fname "${fname}"
+}
+
+
 #
 # Recursively flatten roles into a list of the public key files.
 #
-gpgp::flatten_role() {
+gpgp::flatten_role() (set -euo pipefail
   local role="${1:?must pass role}" ; shift
-  local level="${1:?must pass level}" ; shift
+  local output_indent_level="${1:?must pass output_indent_level}" ; shift
   local verbose="${1:-false}" ; shift
 
   local padding=""
   local one_padding="  "
 
-  for (( i=0; i<level; i++ )); do
+  for (( i=0; i<output_indent_level; i++ )); do
     padding+="${one_padding}"
   done
 
   if ! gpgp::is_role "${role}"; then
-    >&2 echo "couldn't find role: ${role}"
-    exit 1
+    echo "couldn't find role: ${role}"
+    return 2
   fi
 
   if [[ "${verbose}" == "true" ]]; then
@@ -73,42 +108,25 @@ gpgp::flatten_role() {
     fi
 
     if gpgp::is_role "${e}"; then
-      gpgp::flatten_role "${e}" "$((level + 1))" "${verbose}"
-    elif gpgp::match_pub_key "${e}"; then
+      gpgp::flatten_role "${e}" "$((output_indent_level + 1))" "${verbose}"
+    elif gpgp::is_pub_key_auto_role "${e}"; then
+      local key_id="$(gpgp::get_id_from_auto_role "${e}")"
+
       if [[ "${verbose}" == "true" ]]; then
-        echo "${padding}${one_padding}${e}"
+        echo "${padding}${one_padding}${e} (${key_id})"
       else
-        gpgp::get_id_from_key_fname "${e}"
+        echo "${key_id}"
       fi
     else
-      >&2 echo "${e} is not a role or public key"
+      echo "${e} is not a role or public key"
+      return 2
     fi
   done
 
-  if [[ "${verbose}" == "true" ]] && [[ "${level}" == "0" ]]; then
+  if [[ "${verbose}" == "true" ]] && [[ "${output_indent_level}" == "0" ]]; then
     echo
   fi
-}
-
-gpgp::get_id_from_key_fname() {
-  local fname="$1"
-  echo "${fname}" | sed -n -e's/.*id:\([0-9A-Z]\+\).*/\1/p'
-}
-
-_join() {
-  local joint="${1:-}"
-  shift
-  local i=0
-  for e in "$@"; do
-    echo -n "${e}"
-    ((i++))
-    if [[ "${i}" != "$#" ]]; then
-      echo -n "${joint}"
-    else
-      echo
-    fi
-  done
-}
+)
 
 gpgp::recipients_list_from_role() {
   local role="${1}"
@@ -297,6 +315,7 @@ HERE
 
   # convert roles to an array
   local roles=( $@ )
+
   # convention: the last arg is the file to encrypt
   local file="${roles[${#roles[@]}-1]}"
 
@@ -333,19 +352,11 @@ gpgp::secrets_find_role_file() {
   local dir="${1:?must pass dir}" ; shift
   local orig_dir="${dir}"
   local role_file
-  #local role
 
   while true; do
-    #role_file="${dir}/gpgp-role"
     role_file="$(find "${dir}" -maxdepth 1 -type f -name 'gpgp-role:*' | grep --color=never -P '(:.+)')"
 
     if [[ -f "${role_file}" ]]; then
-      #if [[ "$(cat "${role_file}" | wc -l )" != "1" ]] || ! [[ -s "${role_file}" ]]; then
-        #>&2 echo "role file ${role_file} must contain exactly one role."
-        #echo ""
-        #return 1
-      #fi
-
       echo "${role_file}"
       return 0
 
@@ -368,27 +379,6 @@ gpgp::secrets_reencrypt_dir() {
   local dir="${1:?must pass dir}" ; shift
   local dry_run="${1:-false}" ; shift
 
-
-
-
-  #local role_file="$(gpgp::secrets_find_role_file "${dir}")"
-  ## if there's no role file, check if dir only has dirs in it, meaning
-  ## there are no secrets in dir to protect from not being encrypted.
-  #if [[ -z "${role_file}" ]]; then
-    ## how many regular files in are in dir?
-    #if [[ "$(find "${dir}" -maxdepth 1 -name '.git' -prune -o -type f -print | wc -l)" == "0" ]]; then
-      ## if there are none, don't bother to do anything else because the dir has no secrets to encrypt
-      ##:
-      #return 0
-    #else
-      #>&2 echo "role file not found for directory ${dir} or in any parent dir."
-      #return 1
-    #fi
-  #fi
-
-
-
-
   local role_file="$(gpgp::secrets_find_role_file "${dir}")"
   # if there's no role file, check if `dir` has only other directories in it, meaning
   # there are no secrets in `dir` to protect from not being encrypted, and thus it's okay
@@ -398,21 +388,12 @@ gpgp::secrets_reencrypt_dir() {
     # how many regular files in are in dir?
     if [[ "$(find "${dir}" -maxdepth 1 -name '.git' -prune -o -type f -print | wc -l)" == "0" ]]; then
       # if there are none, don't bother to do anything else because the dir has no secrets to encrypt.
-      #:
       return 0
     else
       >&2 echo "role file not found for directory ${dir} or in any parent dir."
       return 1
     fi
   fi
-
-
-
-  # is the role file empty?
-  #local role="$(cat "${role_file}")"
-  #if [[ -z "${role}" ]]; then
-    #return 1
-  #fi
 
   local role="$(echo "${role_file}" | grep --color=never -oP '(?<=:).*')"
 
@@ -614,21 +595,13 @@ gpgp::cmd_reencrypt_dirs() {
 
 gpgp::usage() {
   cat <<HERE
-gpgp ROLES...
+usage: gpgp SUBCMD [OPTIONS] ...
 
-Reads from STDIN, writes to STDOUT in ascii armor.
-
-
-gpgp ROLES... FILE
-
-Encrypts FILE without ascii armor in the same dir.
-
-
-gpgp SUBCMD
+SUBCMD defaults to encrypt.
 
 Subcommands:
 
-(run with -h for more)
+(run each subcommand with -h for more info)
 
 encrypt     Ecrypt a file with one or more roles.
 recips      Prints a \`-r FOOBAR -r BAR...\` string for use with gpg.
@@ -648,8 +621,31 @@ gpgp::assert_gpgp_config() {
   return 0
 }
 
+# TODO dont let a role be the same string that a pubkey starts with
+# TODO always encrypt with admins
+gpgp::assert_roles_valid() {
+  local roles="$(gpgp::ls_roles)"
+
+  local output
+  local rv='0'
+
+  for role in ${roles}; do
+    output="$(
+      gpgp::flatten_role "${role}" 0 true
+    )" || { rv=$? ; }
+
+    if [[ "${rv}" -ne 0 ]]; then
+      echo "${output}"
+      return 1
+    fi
+  done
+
+  return 0
+}
+
 main() {
   gpgp::assert_gpgp_config
+  gpgp::assert_roles_valid
 
   local cmd="${1:-}"
 
@@ -659,6 +655,11 @@ main() {
   fi
 
   case "${cmd}" in
+    -h|--help|help)
+      gpgp::usage
+      exit 1
+      ;;
+
     recips)
       shift
       local roles="$@"
