gpgp: add _manual role

diff --git a/bin/gpgp b/bin/gpgp
--- a/bin/gpgp
+++ b/bin/gpgp
@@ -11,6 +11,13 @@ set -euo pipefail
 [ -n "${GPGP_VERBOSE:-}" ] && set -x
 
 GPG='gpg2'
+COPY=''
+
+if [[ "${OSTYPE}" == "linux-gnu" ]] && which xsel > /dev/null; then
+  COPY='xsel -ib'
+elif [[ "${OSTYPE}" == "darwin"* ]]; then
+  COPY='pbcopy'
+fi
 
 _join() {
   local joint="${1:-}"
@@ -49,6 +56,10 @@ gpgp::ls_pub_keys() {
 
 gpgp::is_role() {
   gpgp::ls_roles | grep -qP "^${1}$"
+}
+
+gpgp::is_manual_role() {
+  [[ "${1}" == "_manual" ]]
 }
 
 gpgp::is_pub_key_auto_role() {
@@ -122,8 +133,9 @@ gpgp::flatten_role() (set -euo pipefail
   fi
 
   if ! gpgp::is_role "${role}"; then
-    echo "couldn't find role: ${role}"
-    return 2
+    echo "gpgp: couldn't find role during flatten: ${role}"
+    #return 2
+    exit 2
   fi
 
   if [[ "${verbose}" == "true" ]]; then
@@ -376,7 +388,7 @@ gpgp::secrets_reencrypt_dir() {
 
   echo
   echo '======================================'
-  echo -e "target dir:  ${dir}\n"
+  echo "target dir: ${dir}"
 
   local role_file="$(gpgp::secrets_find_role_file "${dir}")"
   # if there's no role file, check if `dir` has only other directories in it, meaning
@@ -385,20 +397,29 @@ gpgp::secrets_reencrypt_dir() {
   # to reencrypt in `dir`.
   if [[ -z "${role_file}" ]]; then
     # how many regular files in are in dir?
-    if [[ "$(find "${dir}" -maxdepth 1 -name '.git' -prune -o -type f -print | wc -l)" == "0" ]]; then
+    if [[ "$(find "${dir}" -maxdepth 1 -name '.git*' -prune -o -type f -print | wc -l)" == "0" ]]; then
       # if there are none, don't bother to do anything else because the dir has no secrets to encrypt.
+      echo "no regular files in dir"
       return 0
     else
       >&2 echo "role file not found for directory ${dir} or in any parent dir."
       return 1
     fi
+  else
+    echo "role file:  ${role_file}"
   fi
 
-  local role="$(echo "${role_file}" | grep --color=never -oP '(?<=:).*')"
-  local roles="${role} admin"
+  echo
 
-  gpgp::validate_roles ${roles}
-  gpgp::cmd_ls true ${roles}
+  local role="$(echo "${role_file}" | grep --color=never -oP '(?<=:).*')"
+
+  if gpgp::is_manual_role "${role}"; then
+    echo "dir is being managed manually"
+    return 0
+  fi
+
+  gpgp::validate_roles ${role}
+  gpgp::cmd_ls true ${role}
   echo "files:"
 
   # if it ends with gpg, re-encrypt.
@@ -412,7 +433,7 @@ gpgp::secrets_reencrypt_dir() {
       # dont ever write the unencrypted secret to disk when reencrypting.
       cat "${secret}" \
         | "${GPG}" -d -o- \
-        | "${GPG}" -e $(gpgp::cmd_recips ${roles}) -o"${tmp_secret}"
+        | "${GPG}" -e $(gpgp::cmd_recips ${role}) -o"${tmp_secret}"
       mv "${tmp_secret}" "${secret}"
     fi
   done
@@ -433,13 +454,13 @@ gpgp::secrets_reencrypt_dir() {
     fi
 
     if [[ "${secret}" != *.cleartext ]]; then
-      gpgp::cmd_encrypt -o '--batch --yes' ${roles} "${secret}"
+      gpgp::cmd_encrypt -o '--batch --yes' ${role} "${secret}"
       rm -v "${secret}"
     fi
   done
 
   if [[ "${any_secrets}" == 'f' ]]; then
-    echo -e "  ${COLOR_LIGHT_PURPLE}no secrets in this dir${COLOR_RESET}"
+    echo -e "  ${COLOR_LIGHT_PURPLE}no secrets in dir${COLOR_RESET}"
   fi
 }
 
@@ -592,6 +613,23 @@ gpgp::cmd_find-secrets() {
   eval find "${DAVINCI_GPGP_SECRETS_PATH}" -type f -name '*.gpg' ${grep_pattern}
 }
 
+gpgp::cmd_copy-secret() {
+  local path="${1:?must pass path}"
+  local secret
+
+  if [[ -f "${path}" ]]; then
+    secret="$(${GPG} -d "${path}")"
+  else
+    return
+  fi
+
+  if [[ "$(echo "${secret}" | wc -l)" == "1" ]]; then
+    echo "${secret}" | tr -d '\n' | ${COPY}
+  else
+    echo "${secret}" | ${COPY}
+  fi
+}
+
 gpgp::cmd_reencrypt_dirs() {
   local dry_run="$1" ; shift
   local secrets_path="$1" ; shift
@@ -614,7 +652,7 @@ gpgp::validate_roles() {
   local roles="$@"
   for role in "$@"; do
     if ! gpgp::is_role "${role}" && ! gpgp::is_pub_key_auto_role "${role}" ; then
-      >&2 echo "couldn't find role: ${role}"
+      >&2 echo "gpgp: couldn't find role: ${role}"
       exit 1
     fi
   done
@@ -728,6 +766,11 @@ main() {
     find-secrets)
       shift
       gpgp::cmd_find-secrets "$@"
+      ;;
+
+    copy-secret)
+      shift
+      gpgp::cmd_copy-secret "$@"
       ;;
 
     reencrypt)
